### ISSUE TITLE
attempting to use docker-compose up -d results in errors

### ISSUE THREAD

**Issue by TheOrdinaryMan** [orangetruth/foundryvtt-raspberry-pi#1]
pi@raspberrypi:~ $ sudo docker-compose up -d
Removing foundry
Recreating 266d27846040_foundry ... error

ERROR: for 266d27846040_foundry  Cannot start service foundry_1: network webproxy not found

ERROR: for foundry_1  Cannot start service foundry_1: network webproxy not found
ERROR: Encountered errors while bringing up the project.
pi@raspberrypi:~ $ 

attemptng to run it without Sudo results in :

ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

please help

**Comment by orangetruth** [comment]
@TheOrdinaryMan delete those lines in the docker-compose file referencing webproxy and it should work. I've updated the instructions
