### ISSUE TITLE
Multiple Foundry Instances Jitsi CORS

### ISSUE THREAD

**Issue by illcom94** [orangetruth/foundryvtt-raspberry-pi#2]
Ever since I added a second foundry instance I can no longer use Jitsi. I get a CORS error now.

Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values 'https://.....duckdns.org, *', but only one is allowed.

I think this may be an issue with the nginx config, but I'm having a hard time figuring out how to fix it.

**Comment by orangetruth** [comment]
Honestly I haven't used the Jitsi module in a long time. My group switched over to Discord & Zoom and have had fewer issues with those platforms. I'm getting the same error you are when I reenable that Jitsi RTC module. The creator of that module is now longer maintaining the Jitisi module and recommends switching to the [LiveKit AVClient](https://foundryvtt.com/packages/avclient-livekit) module [here](https://github.com/luvolondon/fvtt-module-jitsiwebrtc#user-limit-warning). I recommend using something like Discord, Zoom, Google Meet, etc. I'll remove Jitisi from the instructions. Thanks for flagging.
